# Generated by Django 5.1.4 on 2024-12-25 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('this_is_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='post_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='this_is_app.post'),
            preserve_default=False,
        ),
    ]
