# Generated by Django 5.1.4 on 2024-12-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('this_is_app', '0003_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_post',
            field=models.IntegerField(default=0),
        ),
    ]
