# Generated by Django 5.1.4 on 2024-12-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('this_is_app', '0004_post_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.FileField(blank=True, default='media/post_photo/default_photo', null=True, upload_to='post_photo'),
        ),
    ]
