# Generated by Django 5.1.4 on 2024-12-29 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('this_is_app', '0007_alter_post_post_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredlojennieNovosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name_from_user', models.CharField(max_length=250)),
                ('post_descr_from_user', models.TextField(max_length=5000)),
                ('post_photo_from_user', models.FileField(blank=True, default='urodlivaya_zalupa.webp', null=True, upload_to='post_photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_category_from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='this_is_app.categorypost')),
                ('post_from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предложение новостя',
                'verbose_name_plural': 'Предложенные новости',
            },
        ),
    ]
